// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLHdYAsSsJjZBCFxv6wSVBBdZb3lDxLrE',
    appId: '1:674278534552:web:b079ddd44cc93e3dd58fed',
    messagingSenderId: '674278534552',
    projectId: 'garbagedetector-41b07',
    authDomain: 'garbagedetector-41b07.firebaseapp.com',
    storageBucket: 'garbagedetector-41b07.firebasestorage.app',
    measurementId: 'G-ZD3B398R65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVFF0q7HsscO5B9NU0IFVI9nB1HheQnaM',
    appId: '1:674278534552:android:5404265fc775ea37d58fed',
    messagingSenderId: '674278534552',
    projectId: 'garbagedetector-41b07',
    storageBucket: 'garbagedetector-41b07.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqmWionCz_xIJdj0JtF8OKiYI8uQZ1rOE',
    appId: '1:674278534552:ios:87dae5acb4df641fd58fed',
    messagingSenderId: '674278534552',
    projectId: 'garbagedetector-41b07',
    storageBucket: 'garbagedetector-41b07.firebasestorage.app',
    iosBundleId: 'com.example.garbagedetector',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqmWionCz_xIJdj0JtF8OKiYI8uQZ1rOE',
    appId: '1:674278534552:ios:87dae5acb4df641fd58fed',
    messagingSenderId: '674278534552',
    projectId: 'garbagedetector-41b07',
    storageBucket: 'garbagedetector-41b07.firebasestorage.app',
    iosBundleId: 'com.example.garbagedetector',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLHdYAsSsJjZBCFxv6wSVBBdZb3lDxLrE',
    appId: '1:674278534552:web:752add6b40d0ce01d58fed',
    messagingSenderId: '674278534552',
    projectId: 'garbagedetector-41b07',
    authDomain: 'garbagedetector-41b07.firebaseapp.com',
    storageBucket: 'garbagedetector-41b07.firebasestorage.app',
    measurementId: 'G-0SP9ZTT497',
  );
}
